version: '3.8'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    container_name: grpc-server
    ports:
      - "50051:50051"

  rest-server:
    build:
      context: .
      dockerfile: Dockerfile.rest
    container_name: rest-server
    ports:
      - "8000:8000"
    depends_on:
      - grpc-server
    environment:
      - GRPC_SERVER_HOST=grpc-server
      - GRPC_SERVER_PORT=50051
